artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.usercontent.google.com/download?id=10njB2Lk9vLYeV9mDQepba_5EViz4limm&authuser=0&confirm=t
  local_data_file: artifacts/data_ingestion/deepfake_data.zip
  unzip_dir: artifacts/data_ingestion