artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.usercontent.google.com/download?id=10njB2Lk9vLYeV9mDQepba_5EViz4limm&authuser=0&confirm=t
  local_data_file: artifacts/data_ingestion/deepfake_data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5